databases:
  - name: nexus-db
    databaseName: nexus_db
    user: nexus_user

services:
  - type: web
    name: nexus-01
    runtime: python
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && pip install -r requirements.txt
    startCommand: cd backend && python run.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nexus-db
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
